version: '3.8'

services:
  postgres:
    image: postgres:15.7
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpassword
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "8085:8085"
    environment:
      DATABASE_URL: postgresql://chatuser:chatpassword@postgres:5432/chat_db?sslmode=disable
      STREAM_API_KEY: nmm45j434zab
      STREAM_API_SECRET: cpevjc7frmegz6qycweygjr2j3u6ynyjgeq2aqfmkkuyk4dukxcfb3d6t6bkrh72
      JWT_SECRET: 2f45e8b25269ccfcc4748c9ada7e731af084b20abfe419bb7a54928bbb5e1cb8
      MIGRATE_DB: true
      PORT: "8085"
    depends_on:
      - postgres

volumes:
  postgres_data: